In [1]:
import rasterio
import numpy as np 

def calculate_aspect(dem):
    with rasterio.open(dem) as dem:
        elevation = dem.read(1)
        transform = dem.transform
        cell_size_x = transform[0]
        cell_size_y = -transform[4]

        dzdx = np.gradient(elevation, axis=1) / cell_size_x
        dzdy = np.gradient(elevation, axis=0) / cell_size_y

        aspect = np.arctan2(-dzdy, dzdx)
        aspect = np.degrees(aspect)
        aspect = (aspect + 360) % 360

        print(aspect)

dem_path = 'AK22_Lamb_be/LAMB_GEG_01M.tif'
calculate_aspect(dem_path)


[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
